
model:
  psz: 15
  model_fname: "/home/beams/SVESELI/edgeBragg/models/feb402psz15.pth"

frame:
  dark_h5: null
  min_intensity: 100
  offset_recover: 0 # a[a>0] += offset_recover
  pvkey: "" # should not be needed
  nproc: 1 # number of processes for frame preproc
  max_radius: 3000
  min_peak_sz: 3 # minimum number of non-pixel
  datatype: "ushortValue" # should not be needed
  
infer:
  tensorrt: False
  mbsz: 1024 
  #mbsz: 16

output:
  #frame2file: "/home/beams/SVESELI/edgeBragg/data/frames.h5"
  frame2file: null
  #peaks2file: "/home/beams/SVESELI/edgeBragg/data/peaks.h5"
  peaks2file: null
  #port4zmq: 5678
  port4zmq: null
